# SPDX-License-Identifier: MIT
# Copyright (c) 2026 The Eke Hive Authors
"""Shared CPU-only build helper for hive host-logic tests (no GPU, no CUDA toolkit).

Production sources are compiled unchanged against tools/cpu_fake/include (fake CUDA,
cuBLAS, NUMA). HIVE_TEST_SANITIZER selects -fsanitize (default: undefined).
"""
import os
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]
FAKE = Path(__file__).resolve().parent


def sanitizer():
    return os.environ.get('HIVE_TEST_SANITIZER', 'undefined')


def flags(extra_opt='-O1'):
    san = sanitizer()
    out = ['g++', '-std=c++20', extra_opt, '-g', '-pthread', '-mavx2', '-mfma', '-mf16c',
           '-I' + str(FAKE / 'include'), '-I' + str(ROOT / 'engine/include'), '-I' + str(ROOT / 'engine/third_party'),
           '-DHIVE_BUILD_ID="cpu-fake"']
    if san and san != 'none':
        out += ['-fsanitize=' + san, '-fno-sanitize-recover=all', '-fno-omit-frame-pointer']
    return out


def build(out_dir, name, code, sources=(), extra=()):
    """Compile `code` (a C++ string, may be empty) plus production/fixture `sources`."""
    exe = str(Path(out_dir) / name)
    cmd = flags() + list(extra)
    inputs = []
    if code:
        src = Path(out_dir) / (name + '.cpp')
        src.write_text(code)
        inputs.append(str(src))
    inputs += [str(s) for s in sources]
    subprocess.run(cmd + inputs + ['-o', exe], check=True)
    return exe


def tsan_env():
    env = dict(os.environ)
    if sanitizer() == 'thread':
        env.setdefault('TSAN_OPTIONS', 'halt_on_error=1:exitcode=66')
    return env


def _slice(text, start, end):
    i = text.index(start)
    return text[i:text.index(end, i)]


def runtime_source():
    """Fake Runtime + PRODUCTION snapshot/reset/option text sliced from runtime.cpp."""
    rt = (ROOT / 'engine/src/runtime.cpp').read_text()
    env_on = _slice(rt, 'bool env_on(const char* name)', '\n') + '\n'
    ctor = _slice(rt, '  if (getenv("HIVE_MTP_CACHE"))', '  if (const char* xp = getenv("HIVE_EXPERT_TRACE")')
    reset = _slice(rt, 'void Runtime::reset_seq(Seq& s) const {', '// ---- Sequence images')
    images = _slice(rt, 'namespace {\nint64_t comp_rows_used', 'void Runtime::dump(const std::string& name')
    tail = _slice(rt, 'bool Runtime::tail_mode_for(int M) const {', 'int32_t Runtime::forward(')
    # promote_after_step (HIVE_PREFILL_PAUSE_PROMOTE) runs on the real ExpertStore (engine/tests/test_runtime_host_cpu.cpp)
    promote = _slice(rt, 'int Runtime::promote_after_step() {', '// Prefill expert pre-copy')
    # Host helpers (tile_plan, host_tile_count, plan_units — the ctor option block calls host_tile_count) and the
    # HostStager class (Runtime owns a unique_ptr<HostStager>; the fake never creates one but ~Runtime needs the complete type)
    helpers = _slice(rt, 'const float* e4m3_lut() {', '// ---- Host helpers END')
    stager = _slice(rt, '// ---- Host tile staging BEGIN', '// ---- Host tile staging END')
    fake = (FAKE / 'fake_runtime.inc').read_text()
    assert fake.count('@@RUNTIME_CTOR_OPTIONS@@') == 1
    head = ('#include "hive/runtime.h"\n#include "hive/kv_pack.h"\n#include "hive/engram_ssd.h"\n#include "hive/pregate.h"\n#include <algorithm>\n#include <chrono>\n#include <cmath>\n'
            '#include <cstring>\n#include <exception>\n#include <functional>\n#include <mutex>\n#include <stdexcept>\n#include <thread>\n'
            'namespace hive {\nnamespace {\n' + env_on + helpers + '}  // namespace\n' + stager + '}  // namespace hive\n')
    return (head + fake.replace('@@RUNTIME_CTOR_OPTIONS@@', ctor) +
            '\n// ---- PRODUCTION text from engine/src/runtime.cpp ----\nnamespace hive {\n' + reset + images + tail + promote + '}  // namespace hive\n')


def host_tiles_source():
    """PRODUCTION host-tile code: the prefill-options helper block (tile_plan, host_tile_count, plan_units) and the
    HostStager class, for tools/cpu_fake/test_host_tiles.cpp (fake CUDA streams — FAKE_CUDA_ASYNC=1 makes them real threads)."""
    rt = (ROOT / 'engine/src/runtime.cpp').read_text()
    helpers = _slice(rt, 'const float* e4m3_lut() {', '// ---- Host helpers END')
    stager = _slice(rt, '// ---- Host tile staging BEGIN', '// ---- Host tile staging END')
    return ('// generated by tools/cpu_fake/harness.py from engine/src/runtime.cpp\n#pragma once\n#include <algorithm>\n#include <functional>\n'
            '#include <mutex>\n#include <thread>\n#include <vector>\n#include "hive/common.h"\n#include "hive/model.h"\nnamespace hive {\nnamespace {\n'
            + helpers + '}  // namespace\n' + stager + '}  // namespace hive\n')


def prefill_helpers_source():
    """PRODUCTION host helpers of the prefill options (runtime.cpp anonymous namespace, e4m3_lut .. END marker)."""
    rt = (ROOT / 'engine/src/runtime.cpp').read_text()
    body = _slice(rt, 'const float* e4m3_lut() {', '// ---- Host helpers END')
    return ('// generated by tools/cpu_fake/harness.py from engine/src/runtime.cpp\n#pragma once\n#include <functional>\n#include <mutex>\n'
            '#include <thread>\n#include <vector>\n#include "hive/common.h"\nnamespace hive {\nnamespace {\n' + body + '}  // namespace\n}  // namespace hive\n')


def objects(out_dir, sources):
    """Compile each source once. HIVE_TEST_BUILD_DIR (set by tools/test_cpu.sh / test_tsan_cpu.sh) shares
    objects between test scripts; the key is a hash of flags + source + every hive header, so a
    changed file is always recompiled."""
    import hashlib
    cache = Path(os.environ.get('HIVE_TEST_BUILD_DIR') or out_dir)
    cache.mkdir(parents=True, exist_ok=True)
    deps = ''.join(p.read_text() for p in sorted((ROOT / 'engine/include/hive').glob('*.h'))) + \
        ''.join(p.read_text() for p in sorted((FAKE / 'include').glob('*.h')))
    objs = []
    for src in sources:
        key = hashlib.sha1((' '.join(flags()) + Path(src).read_text() + deps).encode()).hexdigest()[:12]
        obj = cache / f'{Path(src).stem}-{key}.o'
        if not obj.exists():
            tmp = obj.with_suffix(f'.{os.getpid()}.tmp.o')
            subprocess.run(flags() + ['-c', str(src), '-o', str(tmp)], check=True)
            os.replace(tmp, obj)
        objs.append(obj)
    return objs


def build_daemon(out_dir, name='hived', hived_source=None):
    """The REAL engine/src/hived.cpp + expert_store.cpp + cpu kernels on fake CUDA/Runtime.
    hived_source: optional replacement text (negative-control mutants only; never written to the repo)."""
    gen = Path(out_dir) / 'fake_runtime_gen.cpp'
    gen.write_text(runtime_source())
    src = ROOT / 'engine/src/hived.cpp'
    if hived_source is not None:
        src = Path(out_dir) / (name + '_hived.cpp')
        src.write_text(hived_source)
    objs = objects(out_dir, [src, gen, ROOT / 'engine/src/expert_store.cpp', ROOT / 'engine/src/cpu/expert_cpu.cpp', FAKE / 'fake_checkpoint.cpp'])
    return build(out_dir, name, '', objs)


SUPP = FAKE / 'tsan-known-pool-race.supp'


def tsan_supp_env(env, keep=('items', 'dtor'), tmp_dir=None):
    """Known-race suppressions (tsan-known-pool-race.supp); `keep` selects the [tags] to suppress."""
    if sanitizer() != 'thread':
        return env
    path = SUPP
    if set(keep) != {'items', 'dtor'}:
        out, tag = [], None
        for line in SUPP.read_text().splitlines():
            if line.startswith('# [') and ']' in line:
                tag = line[3:line.index(']')]
            if line.startswith('race:') and tag in keep:
                out.append(line)
        path = Path(tmp_dir) / ('supp-' + '-'.join(keep or ('none',)) + '.supp')
        path.write_text('\n'.join(out) + '\n')
    opts = env.get('TSAN_OPTIONS', 'halt_on_error=1:exitcode=66')
    env['TSAN_OPTIONS'] = opts + ':suppressions=' + str(path)
    return env
