#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 The Eke Hive Authors
"""D4 cache policy replay (engine code as is) — replays an expert trace file under the current policy and the HIVE_CACHE_POLICY policies and compares decode hit rates.

tools/cache_policy_sim.py is an approximation that **rewrites** the policies in Python (its 'hive' approximation diverged from the engine). This tool has no approximation:
  · it builds engine/src/expert_store.cpp **unmodified** against fake CUDA (tools/cpu_fake/include, synchronous mode) — observe, decay, promote, victims, commit,
    seed_scores and the HIVE_CACHE_POLICY policies are all production code (only the record size is reduced to 8 KiB in the Config; slot count and key conventions match production).
  · Runtime::promote_after_step / warm_cache / warm_from_keys and struct RuntimeOptions (defaults) are sliced verbatim from runtime.cpp and runtime.h.
  · What remains = the order in which Runtime calls the store (tools/cache_replay.cpp) — tools/test_cache_replay_cpu.py checks that convention against the runtime.cpp source.
Promotion copies are issued at the end of a step and become resident at commit_pending at the head of the next step (1-step delay — 150 MB/step ≈ 6 ms < 27 ms step).

Usage (no GPU or model needed; a few to a few tens of seconds of CPU):
  python3 tools/cache_replay.py <logs>/expert-trace-XXXX.bin                     # current policy vs all new policies + upper bound (oracle)
  python3 tools/cache_replay.py TRACE --policies current,lfu2 --promote 8 --slots 3792 --cache-state <cache-state.bin>
  Options: --slots (default 3792 = production 71 GB cache), --promote (default 8 = production --promote 8), --promote-misses (default 0 = production off),
        --phase-score 0|1 (default 1 = production HIVE_PHASE_SCORE=1), --eval-from 0.5 (count only the second half), --no-oracle, --json
Output: one line per policy — decode hit = row hits on the token-generation paths (batched decode, verify, draft); decode miss jobs/step = (layer, expert) jobs per step sent to CPU/DMA;
      chunk hit = short prompt chunks (< prefill_threshold, decode policy path); promotions/point = promotions per promotion point (bandwidth); evicted unhit = share of residents
      evicted without a single hit; last line = upper bound (oracle, future-aware promotion with the same budget — not a policy but the size of the headroom). --json prints the full JSON (including per-layer miss jobs).
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FAKE = ROOT / 'tools/cpu_fake'
POLICIES = ('current', 'seq')  # current = HIVE_CACHE_POLICY unset (production default); others = names from parse_cache_policy in engine/src/expert_store.cpp (tuning: 'seq:alpha=8:min=0.025')


def _slice(text: str, start: str, end: str) -> str:
    i = text.index(start)
    return text[i:text.index(end, i)]


def prelude() -> str:
    rt = (ROOT / 'engine/src/runtime.cpp').read_text()
    hdr = (ROOT / 'engine/include/hive/runtime.h').read_text()
    opts = _slice(hdr, 'struct RuntimeOptions {', '\n};') + '\n};\n'
    promote = _slice(rt, 'int Runtime::promote_after_step() {', '// Prefill expert pre-copy')
    warm = _slice(rt, 'int Runtime::warm_cache() {', '// After the head: per-row top-NC candidates')
    warm_keys = _slice(rt, 'int Runtime::warm_from_keys(', '// ---- Sleep / wake')  # the Z1 sleep methods (right after it) are outside the replay
    shell = r'''
class Runtime {  // replay shell: only the members the extracted production methods use (names and types as in runtime.h)
 public:
  Runtime(ExpertStore& s, const RuntimeOptions& o) : store_(s), opt_(o) {
    CUDA_CHECK(cudaStreamCreateWithFlags(&st_, cudaStreamNonBlocking));
    CUDA_CHECK(cudaStreamCreateWithFlags(&promo_, cudaStreamNonBlocking));
    CUDA_CHECK(cudaEventCreateWithFlags(&promo_evt_, cudaEventDisableTiming));
  }
  ExpertStore& store_;
  RuntimeOptions opt_;
  cudaStream_t st_ = nullptr, promo_ = nullptr;
  cudaEvent_t promo_evt_ = nullptr;
  std::vector<int> step_miss_, draft_miss_;
  bool prefill_pause_promote_ = false, prefill_pending_ = false;
  int warm_left_ = 0, warm_step_ = 0, warm_steps_ = 0, warm_done_ = 0;  // HIVE_WARM_DEFER: the replayer never calls warm_defer (quota 0 = the synchronous warm_cache path)
  struct ElasticScope { static void lend_if_idle(Runtime&) {} };  // Q1 HIVE_CACHE_ELASTIC: the replayer only models the off state (no elastic slots)
  int promote_after_step();
  int warm_cache();
  int warm_from_keys(const std::vector<int32_t>& keys);
};
'''
    return ('// generated by tools/cache_replay.py — PRODUCTION text from engine/include/hive/runtime.h and engine/src/runtime.cpp\n'
            '#include "hive/expert_store.h"\n#include "hive/model.h"\n#include <algorithm>\n#include <cmath>\n#include <cstdio>\n#include <string>\n#include <vector>\n'
            'namespace hive {\n' + opts + shell + promote + warm + warm_keys + '}  // namespace hive\n')


def build(out_dir: Path, sanitize: str = 'none', opt_level: str = '-O2', store_source: Path | None = None, store_header: Path | None = None) -> Path:
    """store_source/store_header: source text to use instead of expert_store.cpp/.h (tests only — comparison with the pre-policy version and negative-control mutants. Never written to the repository)."""
    gen = out_dir / 'cache_replay_gen.cpp'
    gen.write_text(prelude() + (ROOT / 'tools/cache_replay.cpp').read_text())
    exe = out_dir / 'cache_replay'
    over = []
    if store_header is not None:  # a same-named header earlier in the include path shadows the one in engine/include
        (out_dir / 'over/hive').mkdir(parents=True, exist_ok=True)
        (out_dir / 'over/hive/expert_store.h').write_text(Path(store_header).read_text())
        over = ['-I' + str(out_dir / 'over')]
    cmd = ['g++', '-std=c++20', opt_level, '-g', '-pthread', '-mavx2', '-mfma', '-mf16c'] + over + ['-I' + str(FAKE / 'include'),
           '-I' + str(ROOT / 'engine/include'), '-I' + str(ROOT / 'engine/third_party'), '-DHIVE_BUILD_ID="cpu-fake"']
    if sanitize and sanitize != 'none':
        cmd += ['-fsanitize=' + sanitize, '-fno-sanitize-recover=all']
    srcs = [gen, store_source or ROOT / 'engine/src/expert_store.cpp', ROOT / 'engine/src/cpu/expert_cpu.cpp', FAKE / 'fake_checkpoint.cpp']
    subprocess.run(cmd + [str(s) for s in srcs] + ['-o', str(exe)], check=True)
    return exe


def run(exe: Path, trace: str, policy: str, args: list[str]) -> dict:
    env = dict(os.environ)
    env.pop('HIVE_CACHE_EVENTS', None)
    if policy == 'current': env.pop('HIVE_CACHE_POLICY', None)
    else: env['HIVE_CACHE_POLICY'] = policy
    out = subprocess.run([str(exe), trace] + args, env=env, check=True, capture_output=True, text=True)
    return json.loads(out.stdout.strip().splitlines()[-1])


def main() -> int:
    cli = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    cli.add_argument('traces', nargs='+')
    cli.add_argument('--policies', default=','.join(POLICIES))
    cli.add_argument('--slots', type=int, default=3792)
    cli.add_argument('--promote', type=int, default=8)
    cli.add_argument('--promote-misses', type=int, default=0)
    cli.add_argument('--phase-score', type=int, default=1)
    cli.add_argument('--cache-state', default='')
    cli.add_argument('--eval-from', type=float, default=0.0)
    cli.add_argument('--no-oracle', action='store_true')
    cli.add_argument('--oracle-window', type=int, default=200, help='upper bound (policy that knows the future): promote with the same budget in order of use count over the next W steps (0 = soonest next use first)')
    cli.add_argument('--json', action='store_true')
    a = cli.parse_args()
    print('REPLAY of production cache code on a recorded trace (routing is cache-independent). Promotions land 1 step later; '
          'DMA contention/timing not modelled — hit rates, not tok/s.', flush=True)
    with tempfile.TemporaryDirectory(prefix='hive-cache-replay-') as td:
        exe = build(Path(td))
        common = ['--slots', str(a.slots), '--promote', str(a.promote), '--promote-misses', str(a.promote_misses),
                  '--phase-score', str(a.phase_score), '--eval-from', str(a.eval_from)]
        if a.cache_state: common += ['--cache-state', a.cache_state]
        for tr in a.traces:
            res = []
            for pol in a.policies.split(','):
                res.append(run(exe, tr, pol, common))
            if not a.no_oracle:
                res.append(run(exe, tr, 'current', common + ['--oracle-window', str(a.oracle_window)]))
            base = res[0]
            print(f"{tr}: steps {base['steps']:,} (decode-path {base['decode_path_steps']:,}) · slots {base['slots']} · promote {a.promote} · "
                  f"warm start {base['warm_start']} · warm_cache {base['warm_cache']} · eval from {a.eval_from:.2f}")
            for r in res:
                d = r['decode_hit_pct'] - base['decode_hit_pct']
                j = 100.0 * (r['decode_jobs_per_step'] / base['decode_jobs_per_step'] - 1) if base['decode_jobs_per_step'] else 0.0
                print(f"  {r['policy'][:26]:26s} decode hit {r['decode_hit_pct']:6.2f}% ({d:+5.2f}) · decode miss jobs/step {r['decode_jobs_per_step']:7.2f} ({j:+5.1f}%) · "
                      f"chunk hit {r['chunk_hit_pct']:6.2f}% · all rows {r['hit_pct']:6.2f}% · promotions/point {r['promotions_per_point']:5.2f} · "
                      f"evicted unhit {r['evicted_unhit'] / max(1, r['evicted']) * 100:4.1f}%", flush=True)
                if a.json: print(json.dumps(r, ensure_ascii=False))
    return 0


if __name__ == '__main__':
    sys.exit(main())
